/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fusionatuoparts;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fatima Zulfikar
 */
public class payments extends javax.swing.JFrame {

    /**
     * Creates new form payments
     */
    public payments() {
        initComponents();
        
    }
     private void insertActionPerformed(java.awt.event.ActionEvent evt) {                                       
    DefaultTableModel model = (DefaultTableModel) ptable.getModel();
    // Retrieve data from text fields
    String paymentID = IDCombo.getSelectedItem().toString();
    float netAmt = Float.parseFloat(netamount.getText());
    float actualAmt = Float.parseFloat(actualpayment.getText());
    float balanceAmt = Float.parseFloat(balance.getText());
    String productID = pcombo.getSelectedItem().toString();
    int quantity = Integer.parseInt(quuantity.getSelectedItem().toString());
    String customerID = cCOMBO.getSelectedItem().toString();

    // Add data to the table
    model.addRow(new Object[]{paymentID, netAmt, actualAmt, balanceAmt, productID, quantity, customerID});
}                                      

private void deleteActionPerformed(java.awt.event.ActionEvent evt) {                                       
    DefaultTableModel model = (DefaultTableModel) ptable.getModel();
    // Check if a row is selected
    int selectedRowIndex = ptable.getSelectedRow();
    if (selectedRowIndex != -1) {
        // Remove the selected row
        model.removeRow(selectedRowIndex);
    } else {
        JOptionPane.showMessageDialog(null, "Please select a row to delete.");
    }
}                                      

private void updateActionPerformed(java.awt.event.ActionEvent evt) {                                       
   
} 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        Discard = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cCOMBO = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ptable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        netamount = new javax.swing.JTextField();
        actualpayment = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        billing = new javax.swing.JButton();
        returntomenu = new javax.swing.JButton();
        pcombo = new javax.swing.JComboBox<>();
        IDCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        quuantity = new javax.swing.JComboBox<>();
        ADD = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        insertP = new javax.swing.JButton();
        Pdelete = new javax.swing.JButton();
        Pupdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fusionatuoparts/icons8-online-payment-32.png"))); // NOI18N
        jLabel1.setText("Payments");

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fusionatuoparts/icons8-save-32.png"))); // NOI18N
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        Discard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fusionatuoparts/icons8-cancel-24.png"))); // NOI18N
        Discard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Discard, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(save)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save)
                    .addComponent(jLabel1)
                    .addComponent(Discard, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Payment ID:");

        jLabel4.setText("Customer ID:");

        jLabel8.setText("Product ID:");

        ptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Payment ID", "Net Amount", "Actual Payment", "Balance", "Product ID", "Quantity", "Customer ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ptable);

        jLabel9.setText("Actual Payment :");

        jLabel11.setText("Balance:");

        billing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fusionatuoparts/icons8-next-page-26.png"))); // NOI18N
        billing.setText("Proceed to billing");
        billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingActionPerformed(evt);
            }
        });

        returntomenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fusionatuoparts/icons8-back-24.png"))); // NOI18N
        returntomenu.setText("Return to Menu");
        returntomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returntomenuActionPerformed(evt);
            }
        });

        jLabel10.setText("Net Amount:");

        ADD.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ADD.setText("+");

        jLabel5.setText("Quantity:");

        insertP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fusionatuoparts/icons8-add-24.png"))); // NOI18N
        insertP.setText("Insert");
        insertP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertPActionPerformed(evt);
            }
        });

        Pdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fusionatuoparts/icons8-delete-24.png"))); // NOI18N
        Pdelete.setText("Delete");
        Pdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PdeleteActionPerformed(evt);
            }
        });

        Pupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fusionatuoparts/icons8-update-24.png"))); // NOI18N
        Pupdate.setText("Update");
        Pupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(insertP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(actualpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(netamount, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                        .addComponent(quuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(61, 61, 61))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(pcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(ADD))))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(cCOMBO, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Pdelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pupdate))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returntomenu)
                            .addComponent(billing))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(IDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(netamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(actualpayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(pcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ADD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cCOMBO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insertP)
                            .addComponent(Pdelete)
                            .addComponent(Pupdate))
                        .addGap(24, 24, 24)
                        .addComponent(billing)
                        .addGap(18, 18, 18)
                        .addComponent(returntomenu))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void billingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingActionPerformed
     bill obj = new bill();
     obj.setVisible(true);
     this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_billingActionPerformed

    private void returntomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returntomenuActionPerformed
    MENU obj = new MENU();
     obj.setVisible(true);
     this.setVisible(false);



        // TODO add your handling code here:
    }//GEN-LAST:event_returntomenuActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
     // Get the default table model
    DefaultTableModel model = (DefaultTableModel) ptable.getModel();
    
    // Retrieve data from text fields and combo boxes
    String paymentID = IDCombo.getSelectedItem().toString();
    float netAmt = Float.parseFloat(netamount.getText());
    float actualAmt = Float.parseFloat(actualpayment.getText());
    float balanceAmt = Float.parseFloat(balance.getText());
    String productID = pcombo.getSelectedItem().toString();
    int quantity = Integer.parseInt(quuantity.getSelectedItem().toString());
    String customerID = cCOMBO.getSelectedItem().toString();

    // Add data to the table
    model.addRow(new Object[]{paymentID, netAmt, actualAmt, balanceAmt, productID, quantity, customerID});
// TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void DiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscardActionPerformed
 // Clear the text fields
    IDCombo.setSelectedIndex(0);
    netamount.setText("");
    actualpayment.setText("");
    balance.setText("");
    pcombo.setSelectedIndex(0);
    quuantity.setSelectedIndex(0);
    cCOMBO.setSelectedIndex(0);
    }//GEN-LAST:event_DiscardActionPerformed

    private void ptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptableMouseClicked
 // Perform actions when a row in the table is clicked
    // For example, you can retrieve data from the selected row
    int selectedRow = ptable.getSelectedRow();
    if (selectedRow != -1) {
        // Example: Get value from the first column of the selected row
        Object value = ptable.getValueAt(selectedRow, 0);
        // Display the value in a message dialog
        JOptionPane.showMessageDialog(this, "Selected row: " + value.toString());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_ptableMouseClicked

    private void insertPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertPActionPerformed
     DefaultTableModel model = (DefaultTableModel) ptable.getModel();
    // Retrieve data from text fields
    String paymentID = IDCombo.getSelectedItem().toString();
    float netAmt = Float.parseFloat(netamount.getText());
    float actualAmt = Float.parseFloat(actualpayment.getText());
    float balanceAmt = Float.parseFloat(balance.getText());
    String productID = pcombo.getSelectedItem().toString();
    int quantity = Integer.parseInt(quuantity.getSelectedItem().toString());
    String customerID = cCOMBO.getSelectedItem().toString();

    // Add data to the table
    model.addRow(new Object[]{paymentID, netAmt, actualAmt, balanceAmt, productID, quantity, customerID}); // TODO add your handling code here:
    }//GEN-LAST:event_insertPActionPerformed

    private void PdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PdeleteActionPerformed
       DefaultTableModel model = (DefaultTableModel) ptable.getModel();
    // Retrieve data from text fields
    String paymentID = IDCombo.getSelectedItem().toString();
    float netAmt = Float.parseFloat(netamount.getText());
    float actualAmt = Float.parseFloat(actualpayment.getText());
    float balanceAmt = Float.parseFloat(balance.getText());
    String productID = pcombo.getSelectedItem().toString();
    int quantity = Integer.parseInt(quuantity.getSelectedItem().toString());
    String customerID = cCOMBO.getSelectedItem().toString();

    // Add data to the table
    model.addRow(new Object[]{paymentID, netAmt, actualAmt, balanceAmt, productID, quantity, customerID});
        // TODO add your handling code here:
    }//GEN-LAST:event_PdeleteActionPerformed

    private void PupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PupdateActionPerformed
       DefaultTableModel model = (DefaultTableModel) ptable.getModel();
    // Retrieve data from text fields
    String paymentID = IDCombo.getSelectedItem().toString();
    float netAmt = Float.parseFloat(netamount.getText());
    float actualAmt = Float.parseFloat(actualpayment.getText());
    float balanceAmt = Float.parseFloat(balance.getText());
    String productID = pcombo.getSelectedItem().toString();
    int quantity = Integer.parseInt(quuantity.getSelectedItem().toString());
    String customerID = cCOMBO.getSelectedItem().toString();

    // Add data to the table
    model.addRow(new Object[]{paymentID, netAmt, actualAmt, balanceAmt, productID, quantity, customerID}); // TODO add your handling code here:
    }//GEN-LAST:event_PupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton Discard;
    private javax.swing.JComboBox<String> IDCombo;
    private javax.swing.JButton Pdelete;
    private javax.swing.JButton Pupdate;
    private javax.swing.JTextField actualpayment;
    private javax.swing.JTextField balance;
    private javax.swing.JButton billing;
    private javax.swing.JComboBox<String> cCOMBO;
    private javax.swing.JButton insertP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField netamount;
    private javax.swing.JComboBox<String> pcombo;
    private javax.swing.JTable ptable;
    private javax.swing.JComboBox<String> quuantity;
    private javax.swing.JButton returntomenu;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
